spring:
  datasource:
    dynamic:
      datasource:
        local:
          url: jdbc:mysql://localhost:3306
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver












